version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.2.0
  - dependency-name: ts-jest
    versions:
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
