sudo: false
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "10"
  - "14"

install:
  - npm i -g yarn
  - yarn install

script:
  - yarn prepublishOnly
  - yarn test --coverage --verbose
