name: Node.js Package

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20

      - uses: actions/cache@v3
        with:
          path: |
            .yarn/cache/
            node_modules/
          key: yarn-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            yarn-cache-

      - name: Install dependencies
        run: yarn

      - name: Testing
        working-directory: pkgs/froute
        run: yarn test

      - name: package-version
        id: package-version
        working-directory: pkgs/froute
        run: echo "name=version::`node -p -e 'require("./package.json").version'` >> $GITHUB_OUTPUT"

      - uses: JS-DevTools/npm-publish@v2
        with:
          provenance: true
          package: pkgs/froute
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ (github.ref == 'refs/heads/dev' && 'dev') || 'latest' }}

      - name: "Check: package version has corrosponding git tag"
        id: tagged
        working-directory: pkgs/froute
        run: git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.package-version.outputs.version }}" && echo "::set-output name=tagged::0" || echo "::set-output name=tagged::1"

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        if: ${{ steps.tagged.outputs.tagged == '0' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.package-version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
