name: Node.js Package

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v1.0.0
        with:
          path: ~/.cache/yarn
          key: yarn-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            yarn-cache-
      - name: Install dependencies
        run: yarn
      - name: Testing
        run: yarn test

      # - name: Check can publish to npm
      #   id: check-publishable
      #   run: |
      #     npx can-npm-publish
      #     if [ $? -eq 1 ] ; then
      #       echo "::set-output name=publishable::false"
      #     else
      #       echo "::set-output name=publishable::true"
      #     fi

      # - name: "Publishing"
      #   if: steps.check-publishable.outputs.publishable == 'true'
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     NODE_AUTH_TOKEN=$NPM_TOKEN yarn publish
      #     NODE_AUTH_TOKEN=$GITHUB_TOKEN yarn publish

      - name: package-version
        id: package-version
        run: echo "::set-output name=version::`node -p -e 'require("./package.json").version'`"

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ (github.ref == 'refs/heads/dev' && 'dev') || 'latest' }}

      - name: "Check: package version has corrosponding git tag"
        id: tagged
        run: git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.package-version.outputs.version }}" && echo "::set-output name=tagged::1" || echo "::set-output name=tagged::0"

      - env:
          TAGGED: ${{ steps.tagged.outputs.tagged }}
        run: echo $TAGGED

      - name: package-version-to-git-tag
        if: ${{ steps.tagged.outputs.tagged == '0' }}
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.package-version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
