name: CI

on: [push]

jobs:
  testing:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.cache/yarn
          key: ${{ matrix.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ matrix.os }}-
      - name: Install deps
        run: yarn install
      - name: Testing @fluer/froute
        run: yarn test --coverage --verbose

  build-lint:
    strategy:
      matrix:
        steps: [build, lint]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.cache/yarn
          key: ${{ matrix.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ matrix.os }}-
      - name: Install deps
        run: yarn install
      # - name: Linting
      #   if: ${{ matrix.steps == 'lint' }}
      #   run: yarn eslint .
      - name: Building
        if: ${{ matrix.steps == 'build' }}
        run: yarn prepublishOnly
